channels:
  #tidair-tag # pcas for rogue
  - lcls-ii
  - conda-forge
  - defaults
  - tidair-packages # pcas for rogue
  - cogsci # pyqode
dependencies:
  - python=3.10
  - setuptools 
  - cmake
  - make
  - gcc_linux-64
  - gxx_linux-64
  - numpy
  - mpi4py   # psana packages (legion is optional)
  - cython
  - matplotlib
  - pytest
  - mongodb
  - pymongo
  - curl
  - mypy_extensions
  - psmon
  - h5py  # needed by small-h5 writer
  - krtc
  - roentdek
  - htop
  - asyncqt # ami
  - setproctitle # ami
  - networkfox # ami
  - pint # ami
  - pyfftw # ami
  - cogsci::pyqode.python # ami
  - pyzmq
  - zeromq
  - pyqt
  - pyqtgraph
  - epics-base
  - readline
  - dill
  - flake8
  - opencv   # xtcav
  - scikit-learn # xtcav and tmo pop alg
  - numba    # ami
  - pydot    # ami
  - pygraphviz # ami
  - qtpy     # ami
  - sympy    # ami
  - pytest-qt # ami testing
  - pytest-asyncio # ami
  - qtconsole # ami
  - p4p      # daq packages
  - libfabric
  - libnl
  - rapidjson
  - jedi=0.17.2
  - transitions
  - ipython
  - requests
  - ipdb
  - prometheus-cpp
  - prometheus_client
  - amityping
  - mypy
  - rogue
  - bluesky
  - ophyd
  - lcls2_timetool
  - cameralink-gateway
  - epix
  - posix_ipc
  - sysv_ipc
  - pyabel  # for tmo pop algorithm
  - git-lfs
  - git
  - lcls2-pgp-pcie-apps
  - caproto
  - scikit-image
  - scikit-beam
  - pytables
  - openmpi
  - lcls2-epix-hr-pcie
  - epix-hr-single-10k
  - gdb
  - holoviews
  - panel
  - aes-stream-drivers
